name: Build & test project

on:
    push:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - uses: actions/checkout@v4
        
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Run unit tests
        working-directory: .
        run: |
          mvn test

