name: Build & test project

on:
    push:
      branches:
        main
    pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Run unit tests
        working-directory: .
        run: |
          mvn test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push the badge (if it changed)
        if: ${{ github.ref_name != 'main' }}
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '*.svg'

          
      - name: Calculate mutation score
        # only calculate mutation score in pull request builds
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: .
        run: |
          # fail the build if mutation score is less than 80%
          mvn test-compile org.pitest:pitest-maven:mutationCoverage -DmutationThreshold=80
          