name: Build & test project

on:
    push:
      branches:
        - main
        - snadi/javamatrix

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]
    name: Java ${{ matrix.Java }} sample

    steps:
      - uses: actions/checkout@v4
        
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Run unit tests
        working-directory: .
        run: |
          mvn test

