name: Build & test project

on:
    pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - uses: actions/checkout@v4
        
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Run unit tests
        working-directory: .
        run: |
          mvn test

      - name: Calculate mutation score
        working-directory: .
        run: |
          # fail the build if mutation score is less than 80%
          mvn test-compile org.pitest:pitest-maven:mutationCoverage -DmutationThreshold=80
  